
networks:
    hadoop-net:
        driver: bridge

services:

  namenode:
    build: ./NameNode
    image: angahez/hadoop-namenode:latest
    container_name: namenode
    hostname: namenode
    ports:
        - "9870:9870"
    networks:
        - hadoop-net
    command: /opt/bd/start-daemons.sh

  resourcemanager:
    build: ./ResourceManager
    image: angahez/hadoop-resourcemanager:latest
    container_name: resourcemanager
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
        - "8088:8088"
    networks:
        - hadoop-net

  dnnm:
    build: ./DataNode-NodeManager
    image: angahez/hadoop-datanode-and-nodemanager:latest
    depends_on:
        - namenode
        - resourcemanager
    command: /opt/bd/start-daemons.sh
    networks:
        - hadoop-net

  jupyter:
    build: ./Jupyter-notebooks
    image: angahez/hadoop-jupyter-notebooks:latest
    depends_on:
        - namenode
        - resourcemanager
        - dnnm
    container_name: hadoop-jupyter
    hostname: jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - hadoop-net
    environment:
      - HDFS_NAMENODE_URI=hdfs://namenode:9000
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      